title: Aaron Mulvihill
description: Personal website
url: "https://moltovivo.github.io"
baseurl: "/personal-site-2025"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

# Collections
collections:
  podcasts:
    output: false

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: default
